/*
 * generated by Xtext
 */
package ie.lero.xacml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XACDLUiModule extends ie.lero.xacml.ui.AbstractXACDLUiModule {
	public XACDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
