/*
 * generated by Xtext
 */
package ie.lero.xacml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XACDLRuntimeModule extends ie.lero.xacml.AbstractXACDLRuntimeModule {

}
