/*
* generated by Xtext
*/
package ie.lero.xacml;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XACDLStandaloneSetup extends XACDLStandaloneSetupGenerated{

	public static void doSetup() {
		new XACDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

