/*
 * generated by Xtext
 */
package ie.lero.xacml.ui.contentassist

import ie.lero.xacml.ui.contentassist.AbstractXACDLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XACDLProposalProvider extends AbstractXACDLProposalProvider {
}
